export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_ERROR: 'GET_INGREDIENTS_ERROR' = 'GET_INGREDIENTS_ERROR';

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_ERROR: 'GET_ORDER_ERROR' = 'GET_ORDER_ERROR';
export const OPEN_ORDER_MODAL: 'OPEN_ORDER_MODAL' = 'OPEN_ORDER_MODAL';
export const CLOSE_ORDER_MODAL: 'CLOSE_ORDER_MODAL' = 'CLOSE_ORDER_MODAL';

export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
export const CLEAR_CONSTRUCTOR: 'CLEAR_CONSTRUCTOR' = 'CLEAR_CONSTRUCTOR';

export const ARRAY_DRAG_MOVE: 'ARRAY_DRAG_MOVE' = 'ARRAY_DRAG_MOVE';

export const GET_INGREDIENT: 'GET_INGREDIENT' = 'GET_INGREDIENT';
export const DEL_INGREDIENT: 'DEL_INGREDIENT' = 'DEL_INGREDIENT';
export const OPEN_INGREDIENT_MODAL: 'OPEN_INGREDIENT_MODAL' = 'OPEN_INGREDIENT_MODAL';
export const CLOSE_INGREDIENT_MODAL: 'CLOSE_INGREDIENT_MODAL' = 'CLOSE_INGREDIENT_MODAL';

export const GET_FORGOT_PASSWORD_REQUEST: 'GET_FORGOT_REQUEST' = 'GET_FORGOT_REQUEST';
export const GET_FORGOT_PASSWORD_SUCCESS: 'GET_FORGOT_SUCCESS' = 'GET_FORGOT_SUCCESS';
export const GET_FORGOT_PASSWORD_ERROR: 'GET_FORGOT_ERROR' = 'GET_FORGOT_ERROR';

export const GET_RESET_PASSWORD_REQUEST: 'GET_RECOVERY_PASSWORD_REQUEST' = 'GET_RECOVERY_PASSWORD_REQUEST';
export const GET_RESET_PASSWORD_SUCCESS: 'GET_RECOVERY_PASSWORD_SUCCESS' = 'GET_RECOVERY_PASSWORD_SUCCESS';
export const GET_RESET_PASSWORD_ERROR: 'GET_RECOVERY_PASSWORD_ERROR' = 'GET_RECOVERY_PASSWORD_ERROR';

export const GET_CREATE_USER_REQUEST: 'GET_CREATE_USER_REQUEST' = 'GET_CREATE_USER_REQUEST';
export const GET_CREATE_USER_SUCCESS: 'GET_CREATE_USER_SUCCESS' = 'GET_CREATE_USER_SUCCESS';
export const GET_CREATE_USER_ERROR: 'GET_CREATE_USER_ERROR' = 'GET_CREATE_USER_ERROR';

export const GET_AUTHORIZATION_REQUEST: 'GET_AUTHORIZATION_REQUEST' = 'GET_AUTHORIZATION_REQUEST';
export const GET_AUTHORIZATION_SUCCESS: 'GET_AUTHORIZATION_SUCCESS' = 'GET_AUTHORIZATION_SUCCESS';
export const GET_AUTHORIZATION_ERROR: 'GET_AUTHORIZATION_ERROR' = 'GET_AUTHORIZATION_ERROR';

export const GET_LOGOUT_REQUEST: 'GET_LOGOUT_REQUEST' = 'GET_LOGOUT_REQUEST';
export const GET_LOGOUT_SUCCESS: 'GET_LOGOUT_SUCCESS' = 'GET_LOGOUT_SUCCESS';
export const GET_LOGOUT_ERROR: 'GET_LOGOUT_ERROR' = 'GET_LOGOUT_ERROR';

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_ERROR: 'GET_USER_ERROR' = 'GET_USER_ERROR';

export const EDIT_USER_REQUEST: 'EDIT_USER_REQUEST' = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS' = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR: 'EDIT_USER_ERROR' = 'EDIT_USER_ERROR';

export const DELETE_USER: 'DELETE_USER' = 'DELETE_USER';

export const REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST' = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_ERROR: 'REFRESH_TOKEN_ERROR' = 'REFRESH_TOKEN_ERROR';

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_ORDERS: 'WS_GET_ORDERS' = 'WS_GET_ORDERS';
export const WS_SEND_ORDERS: 'WS_SEND_ORDERS' = 'WS_SEND_ORDERS';

export default function checkResponse(res: Response) {
    if (!res.ok) {
        throw new Error("Сервер не отвечает.");
    }
    return res.json();
}